import React from 'react'
import type { Metadata } from "next";
import Niat from './Niat'

export const metadata: Metadata = {
    title: "Awas Imsak! - Niat Puasa Bulan Ramadhan",
    description: "Generated by create next app",
  };

const NiatPage = () => {
  return (
    <div><Niat /></div>
  )
}

export default NiatPage