import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Awas Imsak! - Jadwal Sholat & Imsak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/brand.ico" sizes="any" />
      </head>
      <body className="bodi">{children}</body>
    </html>
  );
}
