import React from 'react'
import type { Metadata } from "next";
import Surah from './Surah'

export const metadata: Metadata = {
    title: "Tadarus - Baca Quran Online",
    description: "Generated by create next app",
  };

const SurahPage = () => {
  return (
    <div><Surah /></div>
  )
}

export default SurahPage