import React from 'react'
import type { Metadata } from "next";
import Resep from './Resep'

export const metadata: Metadata = {
  title: "Awas Imsak! - Resep masak untuk keluarga.",
  description: "Generated by create next app",
};

const ResepPage = () => {
  return (
    <div><Resep/></div>
  )
}

export default ResepPage